# Copyright (c) Microsoft. All rights reserved.
# Licensed under the MIT license. See LICENSE file in the project root for full license information.


#this is a very stupid makefile that has as only purpose the building of the executable of the unitTests
#it already has all the object compiled by the "father" makefile
#and it exists for those cases when there are needed "additional" objects in the link
#so it just needs to link them and MicroMock and CTest archives in a nice executable.

#the following are variables that come from the "father" makefile: 
#OUTDIR: this is where the output goes. reason: avoid duplication in every makefile
#EXECUTABLE_NAME: this is the executable name to be build. Reason: I don't know how to get easily the folder name.
#UNIT_TEST_LIBRARIES: this is MicroMock and CTest libraries

#this is the place where all the "additional regular" (That is, those who come out of "Common" folder goes)
COMMON_OBJECT_DIR=../../src

#these are the additional objects to be linked. It usually will include the "code under test" object and others.
ADDITIONAL_OBJECT_FILES_TO_BE_LINKED=\
	$(COMMON_OBJECT_DIR)/hmacsha256.o \
	$(COMMON_OBJECT_DIR)/buffer.o \
	$(COMMON_OBJECT_DIR)/hmac.o \
	$(COMMON_OBJECT_DIR)/usha.o \
	$(COMMON_OBJECT_DIR)/sha1.o \
	$(COMMON_OBJECT_DIR)/sha224.o \
	$(COMMON_OBJECT_DIR)/sha384-512.o \
	$(COMMON_OBJECT_DIR)/gballoc.o $(COMMON_OBJECT_DIR)/../adapters/lock_pthreads.o \


#these are the C object files
OBJECTS_C=$(wildcard ./*.o)

#these are CPP object files
OBJECTS_CPP=$(wildcard ./*.opp)

$(OUTDIR)/$(EXECUTABLE_NAME): $(OBJECTS_C) $(OBJECTS_CPP)
	$(CC) $(OBJECTS_C) $(OBJECTS_CPP) $(ADDITIONAL_OBJECT_FILES_TO_BE_LINKED) $(UNIT_TEST_LIBRARIES) -o $(OUTDIR)/$(EXECUTABLE_NAME) -lstdc++
	
clean:
	$(RM) $(OUTDIR)/$(EXECUTABLE_NAME)
	