

// Copyright (c) Microsoft. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

//
// Simple implementation of IoTHub LWM2M Config object
//

//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

#include "iotdm_internal.h"
#include "iotdm_dispatchers.h"
#include "config_object.h"

DISPATCHER_FORWARD_DECLARATIONS(object_config);

// Property Indices for for config object
#define INDEX_CONFIG_NAME 0
#define INDEX_CONFIG_VALUE 1
#define INDEX_CONFIG_APPLY 2

void set_default_config_property_values(object_config *obj);
IOTHUB_CLIENT_RESULT on_read_config_name(object_config *obj, char **value);
IOTHUB_CLIENT_RESULT on_write_config_name(object_config *obj, const char *value, size_t length);
IOTHUB_CLIENT_RESULT on_read_config_value(object_config *obj, char **value);
IOTHUB_CLIENT_RESULT on_write_config_value(object_config *obj, const char *value, size_t length);
IOTHUB_CLIENT_RESULT on_exec_config_apply(object_config *obj);


/**********************************************************************************
 * Config setters
 *
 **********************************************************************************/
IOTHUB_CLIENT_RESULT set_config_name(uint16_t instanceId, const char *value)
{
    IOTHUB_CLIENT_RESULT result = IOTHUB_CLIENT_ERROR;
    object_config *obj = get_object_instance(OID_CONFIG, instanceId);
    if (obj != NULL)
    {
        if ((obj->propval_config_name == NULL) || strcmp(obj->propval_config_name, value))
        {
            LogInfo("Config_Name being set to [%s]", value);
            lwm2m_free(obj->propval_config_name);
            obj->propval_config_name = lwm2m_strdup(value);

            obj->resourceUpdated[INDEX_CONFIG_NAME] = (char)true;
        }

        result = IOTHUB_CLIENT_OK;
    }

    return result;
}

IOTHUB_CLIENT_RESULT set_config_value(uint16_t instanceId, const char *value)
{
    IOTHUB_CLIENT_RESULT result = IOTHUB_CLIENT_ERROR;
    object_config *obj = get_object_instance(OID_CONFIG, instanceId);
    if (obj != NULL)
    {
        if ((obj->propval_config_value == NULL) || strcmp(obj->propval_config_value, value))
        {
            LogInfo("Config_Value being set to [%s]", value);
            lwm2m_free(obj->propval_config_value);
            obj->propval_config_value = lwm2m_strdup(value);

            obj->resourceUpdated[INDEX_CONFIG_VALUE] = (char)true;
        }

        result = IOTHUB_CLIENT_OK;
    }

    return result;
}


/**********************************************************************************
 * Config creation and destruction
 *
 **********************************************************************************/
static void destroy_config_object(object_config *obj)
{
    if (obj != NULL)
    {
        lwm2m_free(obj->propval_config_name);
        lwm2m_free(obj->propval_config_value);
        lwm2m_free(obj);
    }
}

static uint16_t g_next_config_instance_id = 0;
static uint16_t get_next_config_instance_id()
{
    return g_next_config_instance_id++;
}

IOTHUB_CLIENT_RESULT create_config_object(IOTHUB_CLIENT_HANDLE h, uint16_t *instanceId)
{
    IOTHUB_CLIENT_RESULT res = IOTHUB_CLIENT_OK;

    res = REGISTER_DISPATCHERS(OID_CONFIG, object_config);
    if (res != IOTHUB_CLIENT_OK)
    {
        LogError("Failed registering dispatchers");
        res = IOTHUB_CLIENT_ERROR;
    }

    else
    {
        object_config *obj = (object_config *)lwm2m_malloc(sizeof(object_config));
        if (obj == NULL)
        {
            LogError("malloc failure");
            res = IOTHUB_CLIENT_ERROR;
        }

        else
        {
            memset(obj,0,sizeof(*obj));
            obj->instanceId = get_next_config_instance_id();
            obj->channelHandle = h;
                
            res = add_dm_object(&object_config_instance_list, obj);
            if (res != IOTHUB_CLIENT_OK)
            {
                LogError("adding Config object to object list");

                destroy_config_object(obj);
                obj = NULL;
            }

            else
            {
                set_default_config_property_values(obj);
            }
        }

        if (instanceId != NULL)
        {
            *instanceId = (obj == NULL) ? 0 : obj->instanceId;
        }
    }

    return res;
}

object_config *get_config_object(uint16_t instanceId)
{
    object_config *obj = NULL;

    (void)get_dm_object(object_config_instance_list, instanceId, (void*)&obj);

    return obj;
}

#define DO_SIGNAL_RESOURCE_CHANGE(index, property) \
    if (obj->resourceUpdated[index]) \
    { \
        on_resource_value_changed(obj->channelHandle, OID_CONFIG, obj->instanceId, property); \
        obj->resourceUpdated[index] = (char)false; \
    }

   
void signal_object_config_resource_changed(void *p)
{
    object_config *obj = (object_config*)p;
    DO_SIGNAL_RESOURCE_CHANGE(INDEX_CONFIG_NAME, PID_CONFIG_NAME)
    DO_SIGNAL_RESOURCE_CHANGE(INDEX_CONFIG_VALUE, PID_CONFIG_VALUE)
    DO_SIGNAL_RESOURCE_CHANGE(INDEX_CONFIG_APPLY, PID_CONFIG_APPLY)
}

BEGIN_READ_DISPATCHER(object_config)
    STRING_READ(PID_CONFIG_NAME, on_read_config_name)
    STRING_READ(PID_CONFIG_VALUE, on_read_config_value)
END_READ_DISPATCHER()

BEGIN_EXEC_DISPATCHER(object_config)
    EXEC(PID_CONFIG_APPLY, on_exec_config_apply)
END_EXEC_DISPATCHER()

BEGIN_WRITE_DISPATCHER(object_config)
    STRING_WRITE(PID_CONFIG_NAME, on_write_config_name)
    STRING_WRITE(PID_CONFIG_VALUE, on_write_config_value)
END_WRITE_DISPATCHER();

BEGIN_OPERATION_LIST(object_config)
    OPERATION(PID_CONFIG_NAME, OP_RW, LWM2M_TYPE_STRING)
    OPERATION(PID_CONFIG_VALUE, OP_RW, LWM2M_TYPE_STRING)
    OPERATION(PID_CONFIG_APPLY, OP_E, LWM2M_TYPE_UNDEFINED)
END_OPERATION_LIST()


