

// Copyright (c) Microsoft. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

//
// Simple implementation of IoTHub LWM2M Firmware Update object
//

//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

#include "iotdm_internal.h"
#include "iotdm_dispatchers.h"
#include "firmwareupdate_object.h"


/**********************************************************************************
 * Firmware Update default property values
 *
 **********************************************************************************/

void set_default_firmwareupdate_property_values(object_firmwareupdate *obj)
{
    obj->propval_firmwareupdate_package = NULL;
    obj->propval_firmwareupdate_packageuri = lwm2m_strdup("");
    set_firmwareupdate_state(obj->instanceId, -1);
    set_firmwareupdate_updateresult(obj->instanceId, -1);
    set_firmwareupdate_pkgname(obj->instanceId, "FirmwareUpdate_PkgName");
    set_firmwareupdate_pkgversion(obj->instanceId, "FirmwareUpdate_PkgVersion");
}

/**********************************************************************************
 * CALLBACK HANDLERS
 *
 **********************************************************************************/
IOTHUB_CLIENT_RESULT on_write_firmwareupdate_package(object_firmwareupdate *obj, void* value, size_t length)
{

    return IOTHUB_CLIENT_NOT_IMPLEMENTED;
}

IOTHUB_CLIENT_RESULT on_write_firmwareupdate_packageuri(object_firmwareupdate *obj, const char *value, size_t length)
{
    IOTHUB_CLIENT_RESULT result = IOTHUB_CLIENT_OK;
    lwm2m_free(obj->propval_firmwareupdate_packageuri);
    obj->propval_firmwareupdate_packageuri = iotdm_strndup(value, length);
    LogInfo("FirmwareUpdate_PackageUri being set to [%s]", obj->propval_firmwareupdate_packageuri);

    if (obj->firmwareupdate_packageuri_write_callback != NULL)
    {
        result = obj->firmwareupdate_packageuri_write_callback(obj);
    }
    return result;
}

IOTHUB_CLIENT_RESULT on_exec_firmwareupdate_update(object_firmwareupdate *obj)
{
    IOTHUB_CLIENT_RESULT result = IOTHUB_CLIENT_NOT_IMPLEMENTED;
    LogInfo("inside execute handler for FirmwareUpdate_Update");
    if (obj->firmwareupdate_update_execute_callback != NULL)
    {
        result = obj->firmwareupdate_update_execute_callback(obj);
    }
    return result;
}

IOTHUB_CLIENT_RESULT on_read_firmwareupdate_state(object_firmwareupdate *obj, int64_t *value)
{
    IOTHUB_CLIENT_RESULT result = IOTHUB_CLIENT_OK;
    if (obj->firmwareupdate_state_read_callback != NULL)
    {
        result = obj->firmwareupdate_state_read_callback(obj);
    }
    if (result == IOTHUB_CLIENT_OK)
    {
        *value = obj->propval_firmwareupdate_state;
        LogInfo("returning %lld for FirmwareUpdate_State", *value);
    }
    return result;
}

IOTHUB_CLIENT_RESULT on_read_firmwareupdate_updateresult(object_firmwareupdate *obj, int64_t *value)
{
    IOTHUB_CLIENT_RESULT result = IOTHUB_CLIENT_OK;
    if (obj->firmwareupdate_updateresult_read_callback != NULL)
    {
        result = obj->firmwareupdate_updateresult_read_callback(obj);
    }
    if (result == IOTHUB_CLIENT_OK)
    {
        *value = obj->propval_firmwareupdate_updateresult;
        LogInfo("returning %lld for FirmwareUpdate_UpdateResult", *value);
    }
    return result;
}

IOTHUB_CLIENT_RESULT on_read_firmwareupdate_pkgname(object_firmwareupdate *obj, char **value)
{
    IOTHUB_CLIENT_RESULT result = IOTHUB_CLIENT_OK;
    if (obj->firmwareupdate_pkgname_read_callback != NULL)
    {
        result = obj->firmwareupdate_pkgname_read_callback(obj);
    }
    if (result == IOTHUB_CLIENT_OK)
    {
        *value = lwm2m_strdup(obj->propval_firmwareupdate_pkgname);
        LogInfo("returning [%s] for FirmwareUpdate_PkgName", *value);
    }
    return result;
}

IOTHUB_CLIENT_RESULT on_read_firmwareupdate_pkgversion(object_firmwareupdate *obj, char **value)
{
    IOTHUB_CLIENT_RESULT result = IOTHUB_CLIENT_OK;
    if (obj->firmwareupdate_pkgversion_read_callback != NULL)
    {
        result = obj->firmwareupdate_pkgversion_read_callback(obj);
    }
    if (result == IOTHUB_CLIENT_OK)
    {
        *value = lwm2m_strdup(obj->propval_firmwareupdate_pkgversion);
        LogInfo("returning [%s] for FirmwareUpdate_PkgVersion", *value);
    }
    return result;
}


