

// Copyright (c) Microsoft. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

//
// Simple implementation of IoTHub LWM2M LWM2M Server object
//

//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

#include "iotdm_internal.h"
#include "iotdm_dispatchers.h"
#include "lwm2mserver_object.h"


/**********************************************************************************
 * LWM2M Server default property values
 *
 **********************************************************************************/

void set_default_lwm2mserver_property_values(object_lwm2mserver *obj)
{
    set_lwm2mserver_shortserverid(obj->instanceId, -1);
    set_lwm2mserver_lifetime(obj->instanceId, -1);
    set_lwm2mserver_defaultminimumperiod(obj->instanceId, -1);
    set_lwm2mserver_defaultmaximumperiod(obj->instanceId, -1);
    set_lwm2mserver_binding(obj->instanceId, "LWM2MServer_Binding");
}

/**********************************************************************************
 * CALLBACK HANDLERS
 *
 **********************************************************************************/
IOTHUB_CLIENT_RESULT on_read_lwm2mserver_shortserverid(object_lwm2mserver *obj, int64_t *value)
{
    IOTHUB_CLIENT_RESULT result = IOTHUB_CLIENT_OK;
    if (obj->lwm2mserver_shortserverid_read_callback != NULL)
    {
        result = obj->lwm2mserver_shortserverid_read_callback(obj);
    }
    if (result == IOTHUB_CLIENT_OK)
    {
        *value = obj->propval_lwm2mserver_shortserverid;
        LogInfo("returning %lld for LWM2MServer_ShortServerID", *value);
    }
    return result;
}

IOTHUB_CLIENT_RESULT on_read_lwm2mserver_lifetime(object_lwm2mserver *obj, int64_t *value)
{
    IOTHUB_CLIENT_RESULT result = IOTHUB_CLIENT_OK;
    if (obj->lwm2mserver_lifetime_read_callback != NULL)
    {
        result = obj->lwm2mserver_lifetime_read_callback(obj);
    }
    if (result == IOTHUB_CLIENT_OK)
    {
        *value = obj->propval_lwm2mserver_lifetime;
        LogInfo("returning %lld for LWM2MServer_Lifetime", *value);
    }
    return result;
}

IOTHUB_CLIENT_RESULT on_write_lwm2mserver_lifetime(object_lwm2mserver *obj, int64_t value)
{
    IOTHUB_CLIENT_RESULT result = IOTHUB_CLIENT_OK;
    LogInfo("LWM2MServer_Lifetime being set to %lld", value);
    obj->propval_lwm2mserver_lifetime = value;

    if (obj->lwm2mserver_lifetime_write_callback != NULL)
    {
        result = obj->lwm2mserver_lifetime_write_callback(obj);
    }
    return result;
}

IOTHUB_CLIENT_RESULT on_read_lwm2mserver_defaultminimumperiod(object_lwm2mserver *obj, int64_t *value)
{
    IOTHUB_CLIENT_RESULT result = IOTHUB_CLIENT_OK;
    if (obj->lwm2mserver_defaultminimumperiod_read_callback != NULL)
    {
        result = obj->lwm2mserver_defaultminimumperiod_read_callback(obj);
    }
    if (result == IOTHUB_CLIENT_OK)
    {
        *value = obj->propval_lwm2mserver_defaultminimumperiod;
        LogInfo("returning %lld for LWM2MServer_DefaultMinimumPeriod", *value);
    }
    return result;
}

IOTHUB_CLIENT_RESULT on_write_lwm2mserver_defaultminimumperiod(object_lwm2mserver *obj, int64_t value)
{
    IOTHUB_CLIENT_RESULT result = IOTHUB_CLIENT_OK;
    LogInfo("LWM2MServer_DefaultMinimumPeriod being set to %lld", value);
    obj->propval_lwm2mserver_defaultminimumperiod = value;

    if (obj->lwm2mserver_defaultminimumperiod_write_callback != NULL)
    {
        result = obj->lwm2mserver_defaultminimumperiod_write_callback(obj);
    }
    return result;
}

IOTHUB_CLIENT_RESULT on_read_lwm2mserver_defaultmaximumperiod(object_lwm2mserver *obj, int64_t *value)
{
    IOTHUB_CLIENT_RESULT result = IOTHUB_CLIENT_OK;
    if (obj->lwm2mserver_defaultmaximumperiod_read_callback != NULL)
    {
        result = obj->lwm2mserver_defaultmaximumperiod_read_callback(obj);
    }
    if (result == IOTHUB_CLIENT_OK)
    {
        *value = obj->propval_lwm2mserver_defaultmaximumperiod;
        LogInfo("returning %lld for LWM2MServer_DefaultMaximumPeriod", *value);
    }
    return result;
}

IOTHUB_CLIENT_RESULT on_write_lwm2mserver_defaultmaximumperiod(object_lwm2mserver *obj, int64_t value)
{
    IOTHUB_CLIENT_RESULT result = IOTHUB_CLIENT_OK;
    LogInfo("LWM2MServer_DefaultMaximumPeriod being set to %lld", value);
    obj->propval_lwm2mserver_defaultmaximumperiod = value;

    if (obj->lwm2mserver_defaultmaximumperiod_write_callback != NULL)
    {
        result = obj->lwm2mserver_defaultmaximumperiod_write_callback(obj);
    }
    return result;
}

IOTHUB_CLIENT_RESULT on_read_lwm2mserver_binding(object_lwm2mserver *obj, char **value)
{
    IOTHUB_CLIENT_RESULT result = IOTHUB_CLIENT_OK;
    if (obj->lwm2mserver_binding_read_callback != NULL)
    {
        result = obj->lwm2mserver_binding_read_callback(obj);
    }
    if (result == IOTHUB_CLIENT_OK)
    {
        *value = lwm2m_strdup(obj->propval_lwm2mserver_binding);
        LogInfo("returning [%s] for LWM2MServer_Binding", *value);
    }
    return result;
}

IOTHUB_CLIENT_RESULT on_write_lwm2mserver_binding(object_lwm2mserver *obj, const char *value, size_t length)
{
    IOTHUB_CLIENT_RESULT result = IOTHUB_CLIENT_OK;
    lwm2m_free(obj->propval_lwm2mserver_binding);
    obj->propval_lwm2mserver_binding = iotdm_strndup(value, length);
    LogInfo("LWM2MServer_Binding being set to [%s]", obj->propval_lwm2mserver_binding);

    if (obj->lwm2mserver_binding_write_callback != NULL)
    {
        result = obj->lwm2mserver_binding_write_callback(obj);
    }
    return result;
}


