// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 14.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace api_generator.Templates
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\Workspaces\azure-iot-sdks\c\iotdm_client\tools\api_generator\Templates\blank_object_x_c.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "14.0.0.0")]
    public partial class blank_object_x_c : blank_object_x_cBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("\r\n");
            
            #line 7 "D:\Workspaces\azure-iot-sdks\c\iotdm_client\tools\api_generator\Templates\blank_object_x_c.tt"
 
var allProps = Program.GetListOfPropertiesToGenerate(ObjectName); 

            
            #line default
            #line hidden
            this.Write("\r\n// Copyright (c) Microsoft. All rights reserved.\r\n// Licensed under the MIT lic" +
                    "ense. See LICENSE file in the project root for full license information.\r\n\r\n//\r\n" +
                    "// Simple implementation of IoTHub LWM2M ");
            
            #line 15 "D:\Workspaces\azure-iot-sdks\c\iotdm_client\tools\api_generator\Templates\blank_object_x_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ObjectName));
            
            #line default
            #line hidden
            this.Write(" object\r\n//\r\n\r\n//     This code was generated by a tool.\r\n//\r\n//     Changes to t" +
                    "his file may cause incorrect behavior and will be lost if\r\n//     the code is re" +
                    "generated.\r\n\r\n#include \"iotdm_internal.h\"\r\n#include \"iotdm_dispatchers.h\"\r\n#incl" +
                    "ude \"");
            
            #line 25 "D:\Workspaces\azure-iot-sdks\c\iotdm_client\tools\api_generator\Templates\blank_object_x_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ObjectCodeName.ToLower()));
            
            #line default
            #line hidden
            this.Write("_object.h\"\r\n\r\nDISPATCHER_FORWARD_DECLARATIONS(");
            
            #line 27 "D:\Workspaces\azure-iot-sdks\c\iotdm_client\tools\api_generator\Templates\blank_object_x_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ObjectStructName));
            
            #line default
            #line hidden
            this.Write(");\r\n\r\n// Property Indices for for ");
            
            #line 29 "D:\Workspaces\azure-iot-sdks\c\iotdm_client\tools\api_generator\Templates\blank_object_x_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ObjectCodeName));
            
            #line default
            #line hidden
            this.Write(" object\r\n");
            
            #line 30 "D:\Workspaces\azure-iot-sdks\c\iotdm_client\tools\api_generator\Templates\blank_object_x_c.tt"

foreach (var prop in allProps)
{

            
            #line default
            #line hidden
            this.Write("#define INDEX_");
            
            #line 34 "D:\Workspaces\azure-iot-sdks\c\iotdm_client\tools\api_generator\Templates\blank_object_x_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(prop.PropertyName.ToUpper()));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 34 "D:\Workspaces\azure-iot-sdks\c\iotdm_client\tools\api_generator\Templates\blank_object_x_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(prop.PropertyIndex));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 35 "D:\Workspaces\azure-iot-sdks\c\iotdm_client\tools\api_generator\Templates\blank_object_x_c.tt"

}

            
            #line default
            #line hidden
            this.Write("\r\nvoid set_default_");
            
            #line 39 "D:\Workspaces\azure-iot-sdks\c\iotdm_client\tools\api_generator\Templates\blank_object_x_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ObjectCodeName));
            
            #line default
            #line hidden
            this.Write("_property_values(");
            
            #line 39 "D:\Workspaces\azure-iot-sdks\c\iotdm_client\tools\api_generator\Templates\blank_object_x_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ObjectStructName));
            
            #line default
            #line hidden
            this.Write(" *obj);\r\n");
            
            #line 40 "D:\Workspaces\azure-iot-sdks\c\iotdm_client\tools\api_generator\Templates\blank_object_x_c.tt"

foreach (var prop in allProps)
{
    if (prop.CanRead)
    { 

            
            #line default
            #line hidden
            
            #line 46 "D:\Workspaces\azure-iot-sdks\c\iotdm_client\tools\api_generator\Templates\blank_object_x_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetReadPrototype(prop)));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 47 "D:\Workspaces\azure-iot-sdks\c\iotdm_client\tools\api_generator\Templates\blank_object_x_c.tt"

    }
    if (prop.CanWrite)
    {

            
            #line default
            #line hidden
            
            #line 52 "D:\Workspaces\azure-iot-sdks\c\iotdm_client\tools\api_generator\Templates\blank_object_x_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetWritePrototype(prop)));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 53 "D:\Workspaces\azure-iot-sdks\c\iotdm_client\tools\api_generator\Templates\blank_object_x_c.tt"

    }
    if (prop.CanExecute)
    {

            
            #line default
            #line hidden
            
            #line 58 "D:\Workspaces\azure-iot-sdks\c\iotdm_client\tools\api_generator\Templates\blank_object_x_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetExecutePrototype(prop)));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 59 "D:\Workspaces\azure-iot-sdks\c\iotdm_client\tools\api_generator\Templates\blank_object_x_c.tt"

    }
}

            
            #line default
            #line hidden
            this.Write("\r\n\r\n/****************************************************************************" +
                    "******\r\n * ");
            
            #line 66 "D:\Workspaces\azure-iot-sdks\c\iotdm_client\tools\api_generator\Templates\blank_object_x_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ObjectName));
            
            #line default
            #line hidden
            this.Write(" setters\r\n *\r\n ******************************************************************" +
                    "****************/\r\n");
            
            #line 69 "D:\Workspaces\azure-iot-sdks\c\iotdm_client\tools\api_generator\Templates\blank_object_x_c.tt"

    foreach (var prop in allProps)
    {
        if (prop.CanRead)
        { 

            
            #line default
            #line hidden
            
            #line 75 "D:\Workspaces\azure-iot-sdks\c\iotdm_client\tools\api_generator\Templates\blank_object_x_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetSetterPrototype(prop)));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n    IOTHUB_CLIENT_RESULT result = IOTHUB_CLIENT_ERROR;\r\n    ");
            
            #line 78 "D:\Workspaces\azure-iot-sdks\c\iotdm_client\tools\api_generator\Templates\blank_object_x_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ObjectStructName));
            
            #line default
            #line hidden
            this.Write(" *obj = get_object_instance(OID_");
            
            #line 78 "D:\Workspaces\azure-iot-sdks\c\iotdm_client\tools\api_generator\Templates\blank_object_x_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ObjectCodeName.ToUpper()));
            
            #line default
            #line hidden
            this.Write(", instanceId);\r\n    if (obj != NULL)\r\n    {\r\n");
            
            #line 81 "D:\Workspaces\azure-iot-sdks\c\iotdm_client\tools\api_generator\Templates\blank_object_x_c.tt"

            switch (prop.ResourceFromXml.Type)
            {
                case LWM2MObjectItemType.Opaque:

            
            #line default
            #line hidden
            this.Write("        // BKTODO\r\n        result = IOTHUB_CLIENT_NOT_IMPLEMENTED;\r\n");
            
            #line 88 "D:\Workspaces\azure-iot-sdks\c\iotdm_client\tools\api_generator\Templates\blank_object_x_c.tt"

                    break;
                case LWM2MObjectItemType.String:

            
            #line default
            #line hidden
            this.Write("        if ((obj->");
            
            #line 92 "D:\Workspaces\azure-iot-sdks\c\iotdm_client\tools\api_generator\Templates\blank_object_x_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(prop.SampleVariableName));
            
            #line default
            #line hidden
            this.Write(" == NULL) || strcmp(obj->");
            
            #line 92 "D:\Workspaces\azure-iot-sdks\c\iotdm_client\tools\api_generator\Templates\blank_object_x_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(prop.SampleVariableName));
            
            #line default
            #line hidden
            this.Write(", value))\r\n        {\r\n            LogInfo(\"");
            
            #line 94 "D:\Workspaces\azure-iot-sdks\c\iotdm_client\tools\api_generator\Templates\blank_object_x_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(prop.PropertyName));
            
            #line default
            #line hidden
            this.Write(" being set to [%s]\", value);\r\n            lwm2m_free(obj->");
            
            #line 95 "D:\Workspaces\azure-iot-sdks\c\iotdm_client\tools\api_generator\Templates\blank_object_x_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(prop.SampleVariableName));
            
            #line default
            #line hidden
            this.Write(");\r\n            obj->");
            
            #line 96 "D:\Workspaces\azure-iot-sdks\c\iotdm_client\tools\api_generator\Templates\blank_object_x_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(prop.SampleVariableName));
            
            #line default
            #line hidden
            this.Write(" = lwm2m_strdup(value);\r\n\r\n            obj->resourceUpdated[INDEX_");
            
            #line 98 "D:\Workspaces\azure-iot-sdks\c\iotdm_client\tools\api_generator\Templates\blank_object_x_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(prop.PropertyName.ToUpper()));
            
            #line default
            #line hidden
            this.Write("] = (char)true;\r\n        }\r\n\r\n        result = IOTHUB_CLIENT_OK;\r\n");
            
            #line 102 "D:\Workspaces\azure-iot-sdks\c\iotdm_client\tools\api_generator\Templates\blank_object_x_c.tt"

                    break;
                case LWM2MObjectItemType.Float:

            
            #line default
            #line hidden
            this.Write("        if (obj->");
            
            #line 106 "D:\Workspaces\azure-iot-sdks\c\iotdm_client\tools\api_generator\Templates\blank_object_x_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(prop.SampleVariableName));
            
            #line default
            #line hidden
            this.Write(" != value)\r\n        {\r\n            LogInfo(\"");
            
            #line 108 "D:\Workspaces\azure-iot-sdks\c\iotdm_client\tools\api_generator\Templates\blank_object_x_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(prop.PropertyName));
            
            #line default
            #line hidden
            this.Write(" being set to %f\", value);\r\n            (obj->");
            
            #line 109 "D:\Workspaces\azure-iot-sdks\c\iotdm_client\tools\api_generator\Templates\blank_object_x_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(prop.SampleVariableName));
            
            #line default
            #line hidden
            this.Write(" = value;\r\n\r\n            obj->resourceUpdated[INDEX_");
            
            #line 111 "D:\Workspaces\azure-iot-sdks\c\iotdm_client\tools\api_generator\Templates\blank_object_x_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(prop.PropertyName.ToUpper()));
            
            #line default
            #line hidden
            this.Write("] = (char)true;\r\n        }\r\n\r\n        result = IOTHUB_CLIENT_OK;\r\n");
            
            #line 115 "D:\Workspaces\azure-iot-sdks\c\iotdm_client\tools\api_generator\Templates\blank_object_x_c.tt"

                    break;
                case LWM2MObjectItemType.Integer:
                case LWM2MObjectItemType.Time:

            
            #line default
            #line hidden
            this.Write("        if (obj->");
            
            #line 120 "D:\Workspaces\azure-iot-sdks\c\iotdm_client\tools\api_generator\Templates\blank_object_x_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(prop.SampleVariableName));
            
            #line default
            #line hidden
            this.Write(" != value)\r\n        {\r\n            LogInfo(\"");
            
            #line 122 "D:\Workspaces\azure-iot-sdks\c\iotdm_client\tools\api_generator\Templates\blank_object_x_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(prop.PropertyName));
            
            #line default
            #line hidden
            this.Write(" being set to %lld\", value);\r\n            obj->");
            
            #line 123 "D:\Workspaces\azure-iot-sdks\c\iotdm_client\tools\api_generator\Templates\blank_object_x_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(prop.SampleVariableName));
            
            #line default
            #line hidden
            this.Write(" = value;\r\n\r\n            obj->resourceUpdated[INDEX_");
            
            #line 125 "D:\Workspaces\azure-iot-sdks\c\iotdm_client\tools\api_generator\Templates\blank_object_x_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(prop.PropertyName.ToUpper()));
            
            #line default
            #line hidden
            this.Write("] = (char)true;\r\n        }\r\n\r\n        result = IOTHUB_CLIENT_OK;\r\n");
            
            #line 129 "D:\Workspaces\azure-iot-sdks\c\iotdm_client\tools\api_generator\Templates\blank_object_x_c.tt"

                    break;
            }

            
            #line default
            #line hidden
            this.Write("    }\r\n\r\n    return result;\r\n}\r\n\r\n");
            
            #line 138 "D:\Workspaces\azure-iot-sdks\c\iotdm_client\tools\api_generator\Templates\blank_object_x_c.tt"

        }
    }

            
            #line default
            #line hidden
            this.Write("\r\n/******************************************************************************" +
                    "****\r\n * ");
            
            #line 144 "D:\Workspaces\azure-iot-sdks\c\iotdm_client\tools\api_generator\Templates\blank_object_x_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ObjectName));
            
            #line default
            #line hidden
            this.Write(" creation and destruction\r\n *\r\n *************************************************" +
                    "*********************************/\r\nstatic void destroy_");
            
            #line 147 "D:\Workspaces\azure-iot-sdks\c\iotdm_client\tools\api_generator\Templates\blank_object_x_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ObjectCodeName));
            
            #line default
            #line hidden
            this.Write("_object(");
            
            #line 147 "D:\Workspaces\azure-iot-sdks\c\iotdm_client\tools\api_generator\Templates\blank_object_x_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ObjectStructName));
            
            #line default
            #line hidden
            this.Write(" *obj)\r\n{\r\n    if (obj != NULL)\r\n    {\r\n");
            
            #line 151 "D:\Workspaces\azure-iot-sdks\c\iotdm_client\tools\api_generator\Templates\blank_object_x_c.tt"

    foreach (var prop in allProps)
    {
        if (prop.ResourceFromXml.Type == LWM2MObjectItemType.String)
        {

            
            #line default
            #line hidden
            this.Write("        lwm2m_free(obj->");
            
            #line 157 "D:\Workspaces\azure-iot-sdks\c\iotdm_client\tools\api_generator\Templates\blank_object_x_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(prop.SampleVariableName));
            
            #line default
            #line hidden
            this.Write(");\r\n");
            
            #line 158 "D:\Workspaces\azure-iot-sdks\c\iotdm_client\tools\api_generator\Templates\blank_object_x_c.tt"

        }
    }

            
            #line default
            #line hidden
            this.Write("        lwm2m_free(obj);\r\n    }\r\n}\r\n\r\nstatic uint16_t g_next_");
            
            #line 166 "D:\Workspaces\azure-iot-sdks\c\iotdm_client\tools\api_generator\Templates\blank_object_x_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ObjectCodeName));
            
            #line default
            #line hidden
            this.Write("_instance_id = 0;\r\nstatic uint16_t get_next_");
            
            #line 167 "D:\Workspaces\azure-iot-sdks\c\iotdm_client\tools\api_generator\Templates\blank_object_x_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ObjectCodeName));
            
            #line default
            #line hidden
            this.Write("_instance_id()\r\n{\r\n    return g_next_");
            
            #line 169 "D:\Workspaces\azure-iot-sdks\c\iotdm_client\tools\api_generator\Templates\blank_object_x_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ObjectCodeName));
            
            #line default
            #line hidden
            this.Write("_instance_id++;\r\n}\r\n\r\nIOTHUB_CLIENT_RESULT create_");
            
            #line 172 "D:\Workspaces\azure-iot-sdks\c\iotdm_client\tools\api_generator\Templates\blank_object_x_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ObjectCodeName));
            
            #line default
            #line hidden
            this.Write("_object(IOTHUB_CLIENT_HANDLE h, uint16_t *instanceId)\r\n{\r\n    IOTHUB_CLIENT_RESUL" +
                    "T res = IOTHUB_CLIENT_OK;\r\n\r\n    res = REGISTER_DISPATCHERS(OID_");
            
            #line 176 "D:\Workspaces\azure-iot-sdks\c\iotdm_client\tools\api_generator\Templates\blank_object_x_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ObjectCodeName.ToUpper()));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 176 "D:\Workspaces\azure-iot-sdks\c\iotdm_client\tools\api_generator\Templates\blank_object_x_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ObjectStructName));
            
            #line default
            #line hidden
            this.Write(");\r\n    if (res != IOTHUB_CLIENT_OK)\r\n    {\r\n        LogError(\"Failed registering" +
                    " dispatchers\");\r\n        res = IOTHUB_CLIENT_ERROR;\r\n    }\r\n\r\n    else\r\n    {\r\n " +
                    "       ");
            
            #line 185 "D:\Workspaces\azure-iot-sdks\c\iotdm_client\tools\api_generator\Templates\blank_object_x_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ObjectStructName));
            
            #line default
            #line hidden
            this.Write(" *obj = (");
            
            #line 185 "D:\Workspaces\azure-iot-sdks\c\iotdm_client\tools\api_generator\Templates\blank_object_x_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ObjectStructName));
            
            #line default
            #line hidden
            this.Write(" *)lwm2m_malloc(sizeof(");
            
            #line 185 "D:\Workspaces\azure-iot-sdks\c\iotdm_client\tools\api_generator\Templates\blank_object_x_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ObjectStructName));
            
            #line default
            #line hidden
            this.Write("));\r\n        if (obj == NULL)\r\n        {\r\n            LogError(\"malloc failure\");" +
                    "\r\n            res = IOTHUB_CLIENT_ERROR;\r\n        }\r\n\r\n        else\r\n        {\r\n" +
                    "            memset(obj,0,sizeof(*obj));\r\n            obj->instanceId = get_next_" +
                    "");
            
            #line 195 "D:\Workspaces\azure-iot-sdks\c\iotdm_client\tools\api_generator\Templates\blank_object_x_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ObjectCodeName));
            
            #line default
            #line hidden
            this.Write("_instance_id();\r\n            obj->channelHandle = h;\r\n                \r\n         " +
                    "   res = add_dm_object(&");
            
            #line 198 "D:\Workspaces\azure-iot-sdks\c\iotdm_client\tools\api_generator\Templates\blank_object_x_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ObjectStructName));
            
            #line default
            #line hidden
            this.Write("_instance_list, obj);\r\n            if (res != IOTHUB_CLIENT_OK)\r\n            {\r\n " +
                    "               LogError(\"adding ");
            
            #line 201 "D:\Workspaces\azure-iot-sdks\c\iotdm_client\tools\api_generator\Templates\blank_object_x_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ObjectName));
            
            #line default
            #line hidden
            this.Write(" object to object list\");\r\n\r\n                destroy_");
            
            #line 203 "D:\Workspaces\azure-iot-sdks\c\iotdm_client\tools\api_generator\Templates\blank_object_x_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ObjectCodeName));
            
            #line default
            #line hidden
            this.Write("_object(obj);\r\n                obj = NULL;\r\n            }\r\n\r\n            else\r\n  " +
                    "          {\r\n                set_default_");
            
            #line 209 "D:\Workspaces\azure-iot-sdks\c\iotdm_client\tools\api_generator\Templates\blank_object_x_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ObjectCodeName));
            
            #line default
            #line hidden
            this.Write("_property_values(obj);\r\n            }\r\n        }\r\n\r\n        if (instanceId != NUL" +
                    "L)\r\n        {\r\n            *instanceId = (obj == NULL) ? 0 : obj->instanceId;\r\n " +
                    "       }\r\n    }\r\n\r\n    return res;\r\n}\r\n\r\n");
            
            #line 222 "D:\Workspaces\azure-iot-sdks\c\iotdm_client\tools\api_generator\Templates\blank_object_x_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ObjectStructName));
            
            #line default
            #line hidden
            this.Write(" *get_");
            
            #line 222 "D:\Workspaces\azure-iot-sdks\c\iotdm_client\tools\api_generator\Templates\blank_object_x_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ObjectCodeName));
            
            #line default
            #line hidden
            this.Write("_object(uint16_t instanceId)\r\n{\r\n    ");
            
            #line 224 "D:\Workspaces\azure-iot-sdks\c\iotdm_client\tools\api_generator\Templates\blank_object_x_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ObjectStructName));
            
            #line default
            #line hidden
            this.Write(" *obj = NULL;\r\n\r\n    (void)get_dm_object(");
            
            #line 226 "D:\Workspaces\azure-iot-sdks\c\iotdm_client\tools\api_generator\Templates\blank_object_x_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ObjectStructName));
            
            #line default
            #line hidden
            this.Write("_instance_list, instanceId, (void*)&obj);\r\n\r\n    return obj;\r\n}\r\n\r\n#define DO_SIG" +
                    "NAL_RESOURCE_CHANGE(index, property) \\\r\n    if (obj->resourceUpdated[index]) \\\r\n" +
                    "    { \\\r\n        on_resource_value_changed(obj->channelHandle, OID_");
            
            #line 234 "D:\Workspaces\azure-iot-sdks\c\iotdm_client\tools\api_generator\Templates\blank_object_x_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ObjectCodeName.ToUpper()));
            
            #line default
            #line hidden
            this.Write(", obj->instanceId, property); \\\r\n        obj->resourceUpdated[index] = (char)fals" +
                    "e; \\\r\n    }\r\n\r\n   \r\nvoid signal_object_");
            
            #line 239 "D:\Workspaces\azure-iot-sdks\c\iotdm_client\tools\api_generator\Templates\blank_object_x_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ObjectCodeName));
            
            #line default
            #line hidden
            this.Write("_resource_changed(void *p)\r\n{\r\n    ");
            
            #line 241 "D:\Workspaces\azure-iot-sdks\c\iotdm_client\tools\api_generator\Templates\blank_object_x_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ObjectStructName));
            
            #line default
            #line hidden
            this.Write(" *obj = (");
            
            #line 241 "D:\Workspaces\azure-iot-sdks\c\iotdm_client\tools\api_generator\Templates\blank_object_x_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ObjectStructName));
            
            #line default
            #line hidden
            this.Write("*)p;\r\n");
            
            #line 242 "D:\Workspaces\azure-iot-sdks\c\iotdm_client\tools\api_generator\Templates\blank_object_x_c.tt"

    foreach (var prop in allProps)
    {

            
            #line default
            #line hidden
            this.Write("    DO_SIGNAL_RESOURCE_CHANGE(INDEX_");
            
            #line 246 "D:\Workspaces\azure-iot-sdks\c\iotdm_client\tools\api_generator\Templates\blank_object_x_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(prop.PropertyName.ToUpper()));
            
            #line default
            #line hidden
            this.Write(", PID_");
            
            #line 246 "D:\Workspaces\azure-iot-sdks\c\iotdm_client\tools\api_generator\Templates\blank_object_x_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(prop.PropertyName.ToUpper()));
            
            #line default
            #line hidden
            this.Write(")\r\n");
            
            #line 247 "D:\Workspaces\azure-iot-sdks\c\iotdm_client\tools\api_generator\Templates\blank_object_x_c.tt"

    }

            
            #line default
            #line hidden
            this.Write("}\r\n\r\nBEGIN_READ_DISPATCHER(");
            
            #line 252 "D:\Workspaces\azure-iot-sdks\c\iotdm_client\tools\api_generator\Templates\blank_object_x_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ObjectStructName));
            
            #line default
            #line hidden
            this.Write(")\r\n");
            
            #line 253 "D:\Workspaces\azure-iot-sdks\c\iotdm_client\tools\api_generator\Templates\blank_object_x_c.tt"

foreach (var prop in allProps)
{
    if (prop.CanRead)
    { 

            
            #line default
            #line hidden
            this.Write("    ");
            
            #line 259 "D:\Workspaces\azure-iot-sdks\c\iotdm_client\tools\api_generator\Templates\blank_object_x_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(prop.PropertyTypeName.ToUpper()));
            
            #line default
            #line hidden
            this.Write("_READ(PID_");
            
            #line 259 "D:\Workspaces\azure-iot-sdks\c\iotdm_client\tools\api_generator\Templates\blank_object_x_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(prop.PropertyName.ToUpper()));
            
            #line default
            #line hidden
            this.Write(", on_read_");
            
            #line 259 "D:\Workspaces\azure-iot-sdks\c\iotdm_client\tools\api_generator\Templates\blank_object_x_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(prop.PropertyName.ToLower()));
            
            #line default
            #line hidden
            this.Write(")\r\n");
            
            #line 260 "D:\Workspaces\azure-iot-sdks\c\iotdm_client\tools\api_generator\Templates\blank_object_x_c.tt"

    }
}

            
            #line default
            #line hidden
            this.Write("END_READ_DISPATCHER()\r\n\r\nBEGIN_EXEC_DISPATCHER(");
            
            #line 266 "D:\Workspaces\azure-iot-sdks\c\iotdm_client\tools\api_generator\Templates\blank_object_x_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ObjectStructName));
            
            #line default
            #line hidden
            this.Write(")\r\n");
            
            #line 267 "D:\Workspaces\azure-iot-sdks\c\iotdm_client\tools\api_generator\Templates\blank_object_x_c.tt"

foreach (var prop in allProps)
{
    if (prop.CanExecute)
    { 

            
            #line default
            #line hidden
            this.Write("    EXEC(PID_");
            
            #line 273 "D:\Workspaces\azure-iot-sdks\c\iotdm_client\tools\api_generator\Templates\blank_object_x_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(prop.PropertyName.ToUpper()));
            
            #line default
            #line hidden
            this.Write(", on_exec_");
            
            #line 273 "D:\Workspaces\azure-iot-sdks\c\iotdm_client\tools\api_generator\Templates\blank_object_x_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(prop.PropertyName.ToLower()));
            
            #line default
            #line hidden
            this.Write(")\r\n");
            
            #line 274 "D:\Workspaces\azure-iot-sdks\c\iotdm_client\tools\api_generator\Templates\blank_object_x_c.tt"

    }
}

            
            #line default
            #line hidden
            this.Write("END_EXEC_DISPATCHER()\r\n\r\nBEGIN_WRITE_DISPATCHER(");
            
            #line 280 "D:\Workspaces\azure-iot-sdks\c\iotdm_client\tools\api_generator\Templates\blank_object_x_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ObjectStructName));
            
            #line default
            #line hidden
            this.Write(")\r\n");
            
            #line 281 "D:\Workspaces\azure-iot-sdks\c\iotdm_client\tools\api_generator\Templates\blank_object_x_c.tt"

foreach (var prop in allProps)
{
    if (prop.CanWrite)
    { 

            
            #line default
            #line hidden
            this.Write("    ");
            
            #line 287 "D:\Workspaces\azure-iot-sdks\c\iotdm_client\tools\api_generator\Templates\blank_object_x_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(prop.PropertyTypeName.ToUpper()));
            
            #line default
            #line hidden
            this.Write("_WRITE(PID_");
            
            #line 287 "D:\Workspaces\azure-iot-sdks\c\iotdm_client\tools\api_generator\Templates\blank_object_x_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(prop.PropertyName.ToUpper()));
            
            #line default
            #line hidden
            this.Write(", on_write_");
            
            #line 287 "D:\Workspaces\azure-iot-sdks\c\iotdm_client\tools\api_generator\Templates\blank_object_x_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(prop.PropertyName.ToLower()));
            
            #line default
            #line hidden
            this.Write(")\r\n");
            
            #line 288 "D:\Workspaces\azure-iot-sdks\c\iotdm_client\tools\api_generator\Templates\blank_object_x_c.tt"

    }
}

            
            #line default
            #line hidden
            this.Write("END_WRITE_DISPATCHER();\r\n\r\nBEGIN_OPERATION_LIST(");
            
            #line 294 "D:\Workspaces\azure-iot-sdks\c\iotdm_client\tools\api_generator\Templates\blank_object_x_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ObjectStructName));
            
            #line default
            #line hidden
            this.Write(")\r\n");
            
            #line 295 "D:\Workspaces\azure-iot-sdks\c\iotdm_client\tools\api_generator\Templates\blank_object_x_c.tt"

foreach (var prop in allProps)
{

            
            #line default
            #line hidden
            this.Write("    OPERATION(PID_");
            
            #line 299 "D:\Workspaces\azure-iot-sdks\c\iotdm_client\tools\api_generator\Templates\blank_object_x_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(prop.PropertyName.ToUpper()));
            
            #line default
            #line hidden
            this.Write(", OP_");
            
            #line 299 "D:\Workspaces\azure-iot-sdks\c\iotdm_client\tools\api_generator\Templates\blank_object_x_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(prop.ResourceFromXml.Operations.ToString()));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 299 "D:\Workspaces\azure-iot-sdks\c\iotdm_client\tools\api_generator\Templates\blank_object_x_c.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(prop.LWM2MTypeText));
            
            #line default
            #line hidden
            this.Write(")\r\n");
            
            #line 300 "D:\Workspaces\azure-iot-sdks\c\iotdm_client\tools\api_generator\Templates\blank_object_x_c.tt"

}

            
            #line default
            #line hidden
            this.Write("END_OPERATION_LIST()\r\n\r\n\r\n");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 306 "D:\Workspaces\azure-iot-sdks\c\iotdm_client\tools\api_generator\Templates\blank_object_x_c.tt"
 

public string ObjectName;

public uint ObjectId;

public int PropertyCount;

public string ObjectCodeName
{
    get
    {
        return ObjectName.Replace(" ","").ToLower();
    }
}

public string ObjectStructName
{
    get
    {
        return "object_" + ObjectCodeName;
    }
}

private string GetReadPrototype(PropertyToGenerate prop)
{
    if (prop.Type == LWM2MObjectItemType.Opaque)
    {
        return "IOTHUB_CLIENT_RESULT on_read_" + prop.PropertyName.ToLower() + "(" + ObjectStructName + " *obj, void **value, size_t *length)";
    }
    else if (prop.Type == LWM2MObjectItemType.String)
    {
        return "IOTHUB_CLIENT_RESULT on_read_" + prop.PropertyName.ToLower() + "(" + ObjectStructName + " *obj, char **value)";
    }
    else
    {
        return "IOTHUB_CLIENT_RESULT on_read_" + prop.PropertyName.ToLower() + "(" + ObjectStructName + " *obj, " + prop.PropertyTypeCodeName + " *value)";
    }
}

private string GetWritePrototype(PropertyToGenerate prop)
{
    if (prop.Type == LWM2MObjectItemType.Opaque)
    {
        return "IOTHUB_CLIENT_RESULT on_write_" + prop.PropertyName.ToLower() + "(" + ObjectStructName + " *obj, " + prop.PropertyTypeCodeName + " value, size_t length)";
    }

    else if (prop.Type == LWM2MObjectItemType.String)
    {
        return "IOTHUB_CLIENT_RESULT on_write_" + prop.PropertyName.ToLower() + "(" + ObjectStructName + " *obj, const char *value, size_t length)";
    }

    else
    {
        return "IOTHUB_CLIENT_RESULT on_write_" + prop.PropertyName.ToLower() + "(" + ObjectStructName + " *obj, " + prop.PropertyTypeCodeName + " value)";
    }
}

private string GetSetterPrototype(PropertyToGenerate prop)
{
    if (prop.Type == LWM2MObjectItemType.Opaque)
    {
        return "IOTHUB_CLIENT_RESULT set_" + prop.PropertyName.ToLower() + "(uint16_t instanceId, " + prop.PropertyTypeCodeName + " value, size_t length)";
    }

    else if (prop.Type == LWM2MObjectItemType.String)
    {
        return "IOTHUB_CLIENT_RESULT set_" + prop.PropertyName.ToLower() + "(uint16_t instanceId, const char *value)";
    }

    else
    {
        return "IOTHUB_CLIENT_RESULT set_" + prop.PropertyName.ToLower() + "(uint16_t instanceId, " + prop.PropertyTypeCodeName + " value)";
    }
}


private string GetExecutePrototype(PropertyToGenerate prop)
{
    return "IOTHUB_CLIENT_RESULT on_exec_" + prop.PropertyName.ToLower() + "("  + ObjectStructName + " *obj)";
}


        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "14.0.0.0")]
    public class blank_object_x_cBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
