// IotClientUnitTestsTemplate.idl : IDL source for IotClientUnitTestsTemplate.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (IotClientUnitTestsTemplate.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";
midl_pragma warning (disable : 2015)
import "vsshell.idl";
midl_pragma warning (default : 2015)

//standard dispids
#define DISPID_Name                     (-800)
#define DISPID_Delete                   (-801)
#define DISPID_Object                   (-802)
#define DISPID_Parent                   (-803)
#define DISPID_NewEnum					(-4)
#define DISPID_Value					(0)

[
	uuid(59ae59b8-f256-4b0c-9c57-6c741b1a25a4),
	version(1.0),
	helpstring("IotClientUnitTestsTemplate 1.0 Type Library")
]
library IotClientUnitTestsTemplateLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");


	[
		uuid(ec625337-5c7b-4d7c-b472-98a4e4b1a93d),
		helpstring("IotClientUnitTestsTemplate Package")
	]
	coclass IotClientUnitTestsTemplatePackage
	{
		[default] interface IVsPackage;
	};
};
