# Copyright (c) Microsoft. All rights reserved.
# Licensed under the MIT license. See LICENSE file in the project root for full license information.

#this is the place where all the "additional regular" (That is, those who come out of "Common" folder goes)
COMMON_OBJECT_DIR=../../src

#these are the additional objects to be linked. It usually will include the "code under test" object and others.
ADDITIONAL_OBJECT_FILES_TO_BE_LINKED=$(COMMON_OBJECT_DIR)/doublylinkedlist.o

#these are the C object files
OBJECTS_C=$(wildcard ./*.o)

#these are CPP object files
OBJECTS_CPP=$(wildcard ./*.opp)

$(OUTDIR)/$(EXECUTABLE_NAME): $(OBJECTS_C) $(OBJECTS_CPP)
	$(CC) $(OBJECTS_C) $(OBJECTS_CPP) $(ADDITIONAL_OBJECT_FILES_TO_BE_LINKED) $(UNIT_TEST_LIBRARIES) -o $(OUTDIR)/$(EXECUTABLE_NAME) -lstdc++
	
clean:
	$(RM) $(OUTDIR)/$(EXECUTABLE_NAME)
	