//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeviceExplorer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Microsoft_IoTHub_ConnectionString {
            get {
                return ((string)(this["Microsoft_IoTHub_ConnectionString"]));
            }
            set {
                this["Microsoft_IoTHub_ConnectionString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Microsoft_ServiceBus_EventHub_ConnectionString {
            get {
                return ((string)(this["Microsoft_ServiceBus_EventHub_ConnectionString"]));
            }
            set {
                this["Microsoft_ServiceBus_EventHub_ConnectionString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Microsoft_ServiceBus_EventHub_EntityPath {
            get {
                return ((string)(this["Microsoft_ServiceBus_EventHub_EntityPath"]));
            }
            set {
                this["Microsoft_ServiceBus_EventHub_EntityPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Microsoft_Protocol_Gateway_Hostname {
            get {
                return ((string)(this["Microsoft_Protocol_Gateway_Hostname"]));
            }
            set {
                this["Microsoft_Protocol_Gateway_Hostname"] = value;
            }
        }
    }
}
