

// Copyright (c) Microsoft. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

//
// Simple implementation of IoTHub LWM2M Config object
//

//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

#include <stdio.h>
#include <string.h>
#include <stdlib.h>

#if defined(WIN32)
#include <windows.h>
#include <tchar.h>
#endif

#include "iothub_lwm2m.h"
#include "iotdm_lwm2m_client_apis.h"
#include "liblwm2m.h"


/**********************************************************************************
 * Callback prototypes
 *
 **********************************************************************************/

IOTHUB_CLIENT_RESULT on_read_config_name(STRING_HANDLE *value);
IOTHUB_CLIENT_RESULT on_write_config_name(STRING_HANDLE value);
IOTHUB_CLIENT_RESULT on_read_config_value(STRING_HANDLE *value);
IOTHUB_CLIENT_RESULT on_write_config_value(STRING_HANDLE value);
IOTHUB_CLIENT_RESULT on_execute_config_apply();

/**********************************************************************************
 * Default property implmentations
 *
 **********************************************************************************/
STRING_HANDLE propval_config_name = NULL;
STRING_HANDLE propval_config_value = NULL;

void set_default_config_values()
{
    propval_config_name = STRING_construct("initial value for propval_config_name");
    propval_config_value = STRING_construct("initial value for propval_config_value");
}

/**********************************************************************************
 * CALLBACK REGISTRATION
 *
 **********************************************************************************/
IOTHUB_CLIENT_RESULT register_all_config_callbacks(IOTHUB_CHANNEL_HANDLE h)
{
    if (
        (IOTHUB_CLIENT_OK != IotHubClient_Config_Name_SetReadCallback(h, on_read_config_name)) ||
        (IOTHUB_CLIENT_OK != IotHubClient_Config_Name_SetWriteCallback(h, on_write_config_name)) ||
        (IOTHUB_CLIENT_OK != IotHubClient_Config_Value_SetReadCallback(h, on_read_config_value)) ||
        (IOTHUB_CLIENT_OK != IotHubClient_Config_Value_SetWriteCallback(h, on_write_config_value)) ||
        (IOTHUB_CLIENT_OK != IotHubClient_Config_Apply_SetExecuteCallback(h, on_execute_config_apply)) ||
        false
        )
    {
        LogError("Failure setting callback in Config object\r\n");

        return IOTHUB_CLIENT_ERROR;
    }

    return IOTHUB_CLIENT_OK;
}

/**********************************************************************************
 * OBJECT REGISTRATION
 *
 **********************************************************************************/
IOTHUB_CLIENT_RESULT register_config_object(IOTHUB_CLIENT_HANDLE h)
{
    set_default_config_values();
    if (IOTHUB_CLIENT_OK != register_all_config_callbacks(h))
    {
        LogError("setting default values for Config object\r\n");

        return IOTHUB_CLIENT_ERROR;
    }

    if (IOTHUB_CLIENT_OK != IoTHubClient_DM_AddNewObject(h, 10241))
    {
        LogError("Failure to add the Config object for client: %p\r\n", h);

        return IOTHUB_CLIENT_ERROR;
    }

    return IOTHUB_CLIENT_OK;
}

/**********************************************************************************
 * CALLBACK HANDLERS
 *
 **********************************************************************************/
IOTHUB_CLIENT_RESULT on_read_config_name(STRING_HANDLE *value)
{
    LogInfo("inside reader for Config_Name\r\n");

    LogInfo("returning [%s]\r\n", STRING_c_str(propval_config_name));
    *value = propval_config_name;

    return IOTHUB_CLIENT_OK;
}

IOTHUB_CLIENT_RESULT on_write_config_name(STRING_HANDLE value)
{
    LogInfo("inside writer for Config_Name\r\n");

    LogInfo("setting to [%s]\r\n", STRING_c_str(value));
    STRING_copy(propval_config_name, STRING_c_str(value));

    return IOTHUB_CLIENT_OK;
}

IOTHUB_CLIENT_RESULT on_read_config_value(STRING_HANDLE *value)
{
    LogInfo("inside reader for Config_Value\r\n");

    LogInfo("returning [%s]\r\n", STRING_c_str(propval_config_value));
    *value = propval_config_value;

    return IOTHUB_CLIENT_OK;
}

IOTHUB_CLIENT_RESULT on_write_config_value(STRING_HANDLE value)
{
    LogInfo("inside writer for Config_Value\r\n");

    LogInfo("setting to [%s]\r\n", STRING_c_str(value));
    STRING_copy(propval_config_value, STRING_c_str(value));

    return IOTHUB_CLIENT_OK;
}

IOTHUB_CLIENT_RESULT on_execute_config_apply()
{
    LogInfo("inside execute handler for Config_Apply\r\n");
    return IOTHUB_CLIENT_OK;
}


