# Copyright (c) Microsoft. All rights reserved.
# Licensed under the MIT license. See LICENSE file in the project root for full license information.

#this is a very stupid makefile that has as only purpose the building of the executable of the unitTests
#it already has all the object compiled by the "father" makefile
#and it exists for those cases when there are needed "additional" objects in the link
#so it just needs to link them and MicroMock and CTest archives in a nice executable.

#the following are variables that come from the "father" makefile: 
#OUTDIR: this is where the output goes. reason: avoid duplication in every makefile
#EXECUTABLE_NAME: this is the executable name to be build. Reason: I don't know how to get easily the folder name.
#UNIT_TEST_LIBRARIES: this is MicroMock and CTest libraries

#this is the place where all the "additional regular" (That is, those who come out of "Common" folder goes)
COMMON_OBJECT_DIR=../../../common/src

#this is the IOTHUB_TEST file location
IOTHUB_TEST_FILES_LOCATION=../../../testtools/iothub_test/src

#these are other libraries that we need
OTHER_LIBRARIES=curl pthread qpid-proton

#this is iothub_client lib
IOTHUBCLIENTLIB=../../build/linux/libiothub_client.a ../../build/linux/libiothub_amqp_transport.a ../../build/linux/libiothub_http_transport.a ../../build/linux/libiothub_mqtt_transport.a

#the other libraries are fed to the command line with -llibName
CC_OTHER_LIBRARIES = $(patsubst %, -l%, $(OTHER_LIBRARIES))

#these are the additional objects to be linked. It usually will include the "code under test" object and others.
ADDITIONAL_OBJECT_FILES_TO_BE_LINKED=$(IOTHUB_TEST_FILES_LOCATION)/iothub_account.o $(IOTHUB_TEST_FILES_LOCATION)/iothubtest.o

#these are the C object files
OBJECTS_C=$(wildcard ./*.o)

#these are CPP object files
OBJECTS_CPP=$(wildcard ./*.opp)

$(OUTDIR)/$(EXECUTABLE_NAME): $(OBJECTS_C) $(OBJECTS_CPP)
	$(CC) $(OBJECTS_C) $(OBJECTS_CPP) $(IOTHUBCLIENTLIB) $(CC_OTHER_LIBRARIES) $(ADDITIONAL_OBJECT_FILES_TO_BE_LINKED) $(UNIT_TEST_LIBRARIES) $(E2E_TEST_LIBRARIES) -lm -L $(HOME)/lib  -o $(OUTDIR)/$(EXECUTABLE_NAME) -lstdc++
	
clean:
	$(RM) $(OUTDIR)/$(EXECUTABLE_NAME)
