//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Amqp
{
    
    internal partial class SRAmqp
    {
        private static System.Resources.ResourceManager manager;
        internal static System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if ((SRAmqp.manager == null))
                {
                    SRAmqp.manager = new System.Resources.ResourceManager("Amqp.SRAmqp", typeof(SRAmqp).Assembly);
                }
                return SRAmqp.manager;
            }
        }
        internal static string GetString(SRAmqp.StringResources id)
        {
            return ((string)(Microsoft.SPOT.ResourceUtility.GetObject(ResourceManager, id)));
        }
        [System.SerializableAttribute()]
        internal enum StringResources : short
        {
            AmqpHandleExceeded = -30720,
            InvalidMapKeyType = -27839,
            LinkNotFound = -26757,
            AmqpUnknownDescriptor = -23641,
            SaslNegoFailed = -23066,
            AmqpTimeout = -21233,
            InvalidAddressFormat = -11168,
            InvalidDeliveryIdOnTransfer = -9930,
            AmqpOperationNotSupported = -8658,
            AmqpHandleNotFound = -8192,
            InvalidFrameSize = -6751,
            InvalidSequenceNumberComparison = 89,
            AmqpInvalidFormatCode = 3446,
            DeliveryLimitExceeded = 3476,
            EncodingTypeNotSupported = 9570,
            AmqpChannelNotFound = 18049,
            AmqpIllegalOperationState = 21850,
            InvalidMapCount = 22186,
            WindowViolation = 26611,
        }
    }
}
