# Microsoft Azure IoT Client Libraries
# Copyright (c) Microsoft Corporation
# All rights reserved. 
# MIT License
# Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated 
# documentation files (the Software), to deal in the Software without restriction, including without limitation 
# the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, 
# and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED *AS IS*, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED 
# TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL 
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF 
# CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
# IN THE SOFTWARE.

#this is a very stupid makefile that has as only purpose the building of the executable of the unitTests
#it already has all the object compiled by the "father" makefile
#and it exists for those cases when there are needed "additional" objects in the link
#so it just needs to link them and MicroMock and CTest archives in a nice executable.

#the following are variables that come from the "father" makefile: 
#OUTDIR: this is where the output goes. reason: avoid duplication in every makefile
#EXECUTABLE_NAME: this is the executable name to be build. Reason: I don't know how to get easily the folder name.
#UNIT_TEST_LIBRARIES: this is MicroMock and CTest libraries

#this is the place where all the "additional regular" (That is, those who come out of "Common" folder goes)
COMMON_OBJECT_DIR=../../../common/src
IOTHUB_CLIENT_ADAPTERS_OBJECT_DIR=../../adapters

#these are the additional objects to be linked. It usually will include the "code under test" object and others.
ADDITIONAL_OBJECT_FILES_TO_BE_LINKED=$(IOTHUB_CLIENT_ADAPTERS_OBJECT_DIR)/mqttapi_paho.o $(COMMON_OBJECT_DIR)/crt_abstractions.o
 
#these are the C object files
OBJECTS_C=$(wildcard ./*.o)

#these are CPP object files
OBJECTS_CPP=$(wildcard ./*.opp)

$(OUTDIR)/$(EXECUTABLE_NAME): $(OBJECTS_C) $(OBJECTS_CPP)
	$(CC) $(OBJECTS_C) $(OBJECTS_CPP) $(ADDITIONAL_OBJECT_FILES_TO_BE_LINKED) $(UNIT_TEST_LIBRARIES) -o $(OUTDIR)/$(EXECUTABLE_NAME) -lstdc++
	
clean:
	$(RM) $(OUTDIR)/$(EXECUTABLE_NAME)
	